/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conteoenergias;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author mr.sebaas
 */
public class VntEnergia extends javax.swing.JFrame {

    /**
     * Creates new form VntEnergia
     */
    public VntEnergia() {
        initComponents();
        setIconImage(getIconImage());
        this.setLocationRelativeTo(null);
        this.w.setText("/10");
        this.etiEnergia.setText("3");
        this.etiRonda.setText("1 ");
    }
    
    
    
 
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/axs.png"));
        return retValue;
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSig1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        menosEnergia = new javax.swing.JButton();
        mssEnergia = new javax.swing.JButton();
        btnSig = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        etiRonda = new javax.swing.JLabel();
        w = new javax.swing.JLabel();
        etiEnergia = new javax.swing.JLabel();
        nada = new javax.swing.JLabel();

        btnSig1.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        btnSig1.setText("Sig. Ronda -->");
        btnSig1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSig1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ENERGIA");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 204, 102));
        setIconImage(getIconImage());
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 61, 246));

        menosEnergia.setFont(new java.awt.Font("Bookman Old Style", 3, 12)); // NOI18N
        menosEnergia.setText("-1");
        menosEnergia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosEnergiaActionPerformed(evt);
            }
        });

        mssEnergia.setFont(new java.awt.Font("Bookman Old Style", 3, 12)); // NOI18N
        mssEnergia.setText("+1 ");
        mssEnergia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mssEnergiaActionPerformed(evt);
            }
        });

        btnSig.setFont(new java.awt.Font("Bookman Old Style", 3, 12)); // NOI18N
        btnSig.setText("R->");
        btnSig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSigActionPerformed(evt);
            }
        });

        btnLimpiar.setFont(new java.awt.Font("Bookman Old Style", 3, 12)); // NOI18N
        btnLimpiar.setText("Lim");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        etiRonda.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        etiRonda.setForeground(new java.awt.Color(255, 255, 102));

        w.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        w.setForeground(new java.awt.Color(255, 255, 255));
        w.setText("/10");

        etiEnergia.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        etiEnergia.setForeground(new java.awt.Color(255, 255, 255));
        etiEnergia.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiEnergia.setText("3");

        nada.setBackground(new java.awt.Color(255, 255, 255));
        nada.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        nada.setForeground(new java.awt.Color(255, 255, 255));
        nada.setText("RONDA ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(etiEnergia, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(w, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(menosEnergia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nada)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(etiRonda, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(mssEnergia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSig)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnLimpiar)))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nada, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiRonda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiEnergia, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(w, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menosEnergia)
                    .addComponent(mssEnergia)
                    .addComponent(btnSig)
                    .addComponent(btnLimpiar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
     
    private int count =0;
    private int ini = 3;
    private int ron = 1;
    private void menosEnergiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosEnergiaActionPerformed
        ini--;
        String numero = String.valueOf(ini);
        etiEnergia.setText(numero);
        if(ini==-1){
            ini++;
            String num = String.valueOf(ini);
            etiEnergia.setText(num);
        }
    }//GEN-LAST:event_menosEnergiaActionPerformed

    private void mssEnergiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mssEnergiaActionPerformed

        ini++; 
        String numero = String.valueOf(ini);
        etiEnergia.setText(numero);
        if(ini>=11){
            ini--;
            String num = String.valueOf(ini);
            etiEnergia.setText(num);
        }
    }//GEN-LAST:event_mssEnergiaActionPerformed

    private void btnSigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSigActionPerformed
        ron++;
        String ronda = String.valueOf(ron);
        etiRonda.setText(ronda);
        if(ini>=8&&ini<=20){
            ini=9;
            ini=ini+1;
            String num = String.valueOf(ini);
            etiEnergia.setText(num);
        }else{
            ini=ini+2;
            String numero = String.valueOf(ini);
            etiEnergia.setText(numero);
        }
    }//GEN-LAST:event_btnSigActionPerformed

    private void btnSig1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSig1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSig1ActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        ini=3;
        String numero = String.valueOf(ini);
        etiEnergia.setText(numero);
        ron=1;
        String ronda = String.valueOf(ron);
        etiRonda.setText(ronda);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSig;
    private javax.swing.JButton btnSig1;
    private javax.swing.JLabel etiEnergia;
    private javax.swing.JLabel etiRonda;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton menosEnergia;
    private javax.swing.JButton mssEnergia;
    private javax.swing.JLabel nada;
    private javax.swing.JLabel w;
    // End of variables declaration//GEN-END:variables
}
